import {Box, HStack, VStack} from '@chakra-ui/react';
import Head from 'next/head';
import React from 'react';

interface LayoutProps {
  children: React.ReactNode;
}

const DefaultLayout: React.FC<LayoutProps> = ({children}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <VStack>
        <Box as='header' w='full'>
          header
        </Box>
        <HStack w='full'>
          <nav>nav</nav>
          <Box as='main' flex='auto'>
            {children}
          </Box>
        </HStack>
      </VStack>
    </>
  );
};

export default DefaultLayout;
