import {Box, Center, HStack, VStack, useDisclosure, IconButton, Avatar} from '@chakra-ui/react';
import {HamburgerMenuIcon} from '@radix-ui/react-icons';
import Head from 'next/head';
import React, {useRef} from 'react';
import SideNav from './SideNav';

interface LayoutProps {
  children: React.ReactNode;
}

const DefaultLayout: React.FC<LayoutProps> = ({children}) => {
  const {isOpen, onOpen, onClose} = useDisclosure();
  const menuBtnRef = useRef(null);

  return (
    <>
      <Head>
        <title>comcat</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <VStack height='100vh' spacing='0'>
        <HStack as='header' w='full' h='16' spacing='2'>
          <Center w='72px' h='full' flex='none'>
            <IconButton
              ref={menuBtnRef}
              onClick={onOpen}
              variant='ghost'
              borderRadius='full'
              aria-label='Menu'
              icon={<HamburgerMenuIcon width='20' height='20' />}
            />
          </Center>
          <Center h='full' flex='none'>
            title
          </Center>
          <Center w='full' h='full' flex='auto'>
            actions
          </Center>
          <Center pr='4'>
            <Avatar size='sm' />
          </Center>
        </HStack>
        <HStack h='full' w='full' flex='auto' spacing='0'>
          <SideNav isOpen={isOpen} placement='left' onClose={onClose} finalFocusRef={menuBtnRef}>
            test
          </SideNav>
          <Box as='main' h='full' flex='auto' background='gray.50'>
            {children}
          </Box>
        </HStack>
      </VStack>
    </>
  );
};

export default DefaultLayout;
